# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbUDzpnGJDvlvGvEWJzuKZM8dfyESxz9

---
# **Anotaciones**

---

Estas son algunas anotaciones para explicar que este notebook se utilizará principalmente para el proyecto final:
Este notebook se creará para llevar a cabo el proyecto final del curso.
Se utilizará para cargar, limpiar y analizar datos.
También se utilizará para crear modelos y visualizaciones que se utilizarán en el proyecto final.
Es importante mantener organizado este notebook para que sea fácil de seguir y entender.
"""

import pandas as pd
import numpy as np
print("¡Hola, Proyecto Final del Curso!")